### ISSUE TITLE
Install error with SICL

### ISSUE THREAD

**Issue by djpeebles** [clasp-developers/clasp#621]
Trying to install Clasp on Linux I get the following output and error below.  I notice that there may have been a relevant change made in commit 4e33e85b89adb7e8f06d02f934c12497e766300b 15 days ago.  Does something need to be updated in the wscript file?

update_dependencies() 
Git repository src/lisp/kernel/contrib/sicl  url: https://github.com/Bike/SICL.git
     revision: 3107189da298e0107c2567a1d9194fa6aa474e00  label: master

Updating git repo at 'src/lisp/kernel/contrib/sicl'
fatal: Could not parse object '3107189da298e0107c2567a1d9194fa6aa474e00'.
Traceback (most recent call last):
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 179, in run_commands
    ctx=run_command(cmd_name)
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 170, in run_command
    ctx.execute()
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/david/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/home/david/clasp/wscript", line 1130, in configure
    update_dependencies(cfg)
  File "/home/david/clasp/wscript", line 275, in update_dependencies
    "3107189da298e0107c2567a1d9194fa6aa474e00")
  File "/home/david/clasp/wscript", line 240, in fetch_git_revision
    raise Exception("Failed to fetch git url %s" % url)
Exception: Failed to fetch git url https://github.com/Bike/SICL.git

**Comment by djpeebles** [comment]
I've re-cloned the master branch and it works now.
