### ISSUE TITLE
Waf: The wscript in '/mnt/clasp' is unreadable

### ISSUE THREAD

**Issue by marespiaut** [clasp-developers/clasp#648]
Hello,

I've tried to build clasp on Arch Linux and I got the following error message:

```
% ./waf configure
Waf: The wscript in '/mnt/clasp' is unreadable
Traceback (most recent call last):
  File "/mnt/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/mnt/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/mnt/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/mnt/clasp/wscript", line 55, in <module>
    from wscript_utils import *
  File "tools-for-build/wscript_utils.py", line 75
    result = result.strip()
                          ^
TabError: inconsistent use of tabs and spaces in indentation
```

I'm not sure if I've missed something, or if Arch Linux is simply unsupported.

Best regards.

**Comment by kpoeck** [comment]
can you try;
python2 waf configure or for everything 
python2 waf distclean configure build_cboehm

**Comment by marespiaut** [comment]
It seems that was the solution. `python2` need to used to execute `waf`.

However, now the problem is that clang 6 isn't available by default on Arch Linux.

**Comment by Bike** [comment]
It will be a little while before we upgrade LLVM. llvm6 looks to be available in AUR in the meantime.

**Comment by kpoeck** [comment]
Original issue fixed, will close when no more comments
