### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by sjatkins** [clasp-developers/clasp#673]
With all considerably due respect this has a lot of niggling issues to even run the make.  Please clean up. 

base) mini:clasp samantha$ make
./waf build_dboehm
Waf: The wscript in '/Users/samantha/work/clasp' is unreadable
Traceback (most recent call last):
  File "/Users/samantha/work/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 102, in waf_entry_point
    set_main_module(wscript)
  File "/Users/samantha/work/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 142, in set_main_module
    Context.g_module=Context.load_module(file_path)
  File "/Users/samantha/work/clasp/.waf3-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 355, in load_module
    exec(compile(code,path,'exec'),module.__dict__)
  File "/Users/samantha/work/clasp/wscript", line 55, in <module>
    from wscript_utils import *
  File "tools-for-build/wscript_utils.py", line 75
    result = result.strip()
                          ^
TabError: inconsistent use of tabs and spaces in indentation
make: *** [all] Error 2
(base) mini:clasp samantha$ emacs tools-for-build/wscript_utils.py
(base) mini:clasp samantha$ make
./waf build_dboehm
reinitialized logger
Running init() - this constructs the matrix of legal waf operation names
The project was not configured: run "waf configure" first!
make: *** [all] Error 1
(base) mini:clasp samantha$ waf configure
-bash: waf: command not found

**Comment by kpoeck** [comment]
Please follow https://github.com/clasp-developers/clasp/wiki/Build-Instructions

**Comment by kpoeck** [comment]
you need python2 as described in the above build instructions, see linux step 4

**Comment by kpoeck** [comment]
fixed make to do the right thing
