### ISSUE TITLE
What is the correct revision of https://github.com/Bike/SICL.git for building?

### ISSUE THREAD

**Issue by vxe** [clasp-developers/clasp#858]
my `waf configure` fails as below

```
Git repository src/lisp/kernel/contrib/sicl  url: https://github.com/Bike/SICL.git
     revision: 1398dbfe5c899a0aa675d8516c424fd004ed7e1e  label: master

Updating git repo at 'src/lisp/kernel/contrib/sicl'
fatal: Could not parse object '1398dbfe5c899a0aa675d8516c424fd004ed7e1e'.
Traceback (most recent call last):
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 119, in waf_entry_point
    run_commands()
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 179, in run_commands
    ctx=run_command(cmd_name)
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Scripting.py", line 170, in run_command
    ctx.execute()
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 85, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/clasp/.waf-2.0.10-21b9fcc8516c313e4e3a81dc239e6d66/waflib/Context.py", line 126, in recurse
    user_function(self)
  File "/clasp/wscript", line 1138, in configure
    update_dependencies(cfg)
  File "/clasp/wscript", line 263, in update_dependencies
    "https://github.com/Bike/SICL.git", "1398dbfe5c899a0aa675d8516c424fd004ed7e1e")
  File "/clasp/wscript", line 253, in fetch_git_revision
    raise Exception("Failed to fetch git url %s" % url)
Exception: Failed to fetch git url https://github.com/Bike/SICL.git
```

https://github.com/clasp-developers/clasp/commit/546b9fe6a9dc10f97bc57deea2d83340bc09b747

**Comment by vxe** [comment]
ok, its gets further when using the `dev` branch...

**Comment by Bike** [comment]
Yeah, use the dev branch. I'll see if I can't fix the master build though.

**Comment by kpoeck** [comment]
From the waf file in dev, the revision is:
    fetch_git_revision("src/lisp/kernel/contrib/sicl",
                       "https://github.com/Bike/SICL.git",
                       "bf49bb239950169e5153e01b4c1d400ff663558d")

**Comment by Bike** [comment]
master's prolly good now
